### ISSUE TITLE
Add Discovery Support for this Adapter

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.km200#2]
Hey,

please check out the Discovery-Adapter (https://github.com/ioBroker/ioBroker.discovery) and check if the device can be detected somehow (special url with defined answer, special port, upnp, udp or other technologies?!). If yes it would great if you could add a pull request to the Discovery-Adapter with the needed code.
Support needed? Contact me (Apollon77) in Forum as forum thread or PN ;-)

Ingo

**Comment by frankjoke** [comment]
will work on this later because I need feedback what the standard host names are which are used by the different devices!
Is there somewhere a description how discovery works and how I can add an adapter?

**Comment by frankjoke** [comment]
Ingo, can it be that your test or js-controller code contains some V8-only syntax?
The adapter was tested all green a week ago and now after I implemented some changes I do get errors on node V6 only!

I am really not happy with the new test routines because of this on and off I get so much unpredictable results not caused by myself!

**Comment by Apollon77** [comment]
Testing sollte daran nicht schuld sein. Link bitte zu Travis.

**Comment by mcm1957** [comment]
replaced by #31
