### ISSUE TITLE
getObjectList  is not a function

### ISSUE THREAD

**Issue by vdcore** [iobroker-community-adapters/ioBroker.km200#37]
`km200.0 | 2020-04-03 11:19:53.751 | error | (2947) err from getObjectList: TypeError: this[_0x775f(...)] is not a function`

Whats Wrong? Can someone fix that issues? 

thx a lot

**Comment by marcnesium2k** [comment]
Hi vdcore,
Please check if you're using V. 2.0.3... (i had to change repository (in german Verwahrungsort" to "latest" in ioBroker admin interface)

BR

**Comment by frankjoke** [comment]
I just started to recover my old VM from a year ago for adapter development and realized that it uses old @iobroker/adapter-core and generates problems on all systems running js-controller >=2.x.

I will need to change @frankjoke/myAdapter (which I did already to Version 1.2.5 on git) but still need to make changes to all my adapters to use the new version.

You may download the new version of it using Admin/git and install `https://github.com/frankjoke/myAdapter`, you will get an error at end because it's not the complete adapter but at least it worked for me on test system.

**Comment by mcm1957** [comment]
Please indicate if this error still occures with latzest version (2.0.5)

Please add all related versions
adapter version:
admin version:
js-controller version:
node version:
operating system and version:

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
